# Generated by Django 5.2.8 on 2025-11-14 12:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertRule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(help_text='Alert rule name', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Description of what this rule detects')),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('condition_type', models.CharField(choices=[('count', 'Event Count'), ('threshold', 'Threshold'), ('spike', 'Spike Detection'), ('pattern', 'Pattern Match')], default='count', max_length=20)),
                ('source_type', models.CharField(blank=True, help_text='Filter by source type (empty = all sources)', max_length=50)),
                ('action', models.CharField(blank=True, help_text='Filter by action (empty = all actions)', max_length=20)),
                ('severity', models.CharField(blank=True, help_text='Filter by severity (empty = all severities)', max_length=20)),
                ('country_code', models.CharField(blank=True, help_text='Filter by country (empty = all countries)', max_length=2)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='Filter by specific IP address', null=True)),
                ('threshold', models.IntegerField(default=10, help_text='Number of events to trigger alert')),
                ('time_window_minutes', models.IntegerField(default=5, help_text='Time window in minutes')),
                ('notification_channels', models.JSONField(default=list, help_text='List of notification channels with encrypted webhooks')),
                ('cooldown_minutes', models.IntegerField(default=15, help_text='Minimum minutes between alerts')),
                ('last_triggered', models.DateTimeField(blank=True, null=True)),
                ('trigger_count', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_alert_rules', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_rules', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Alert Rule',
                'verbose_name_plural': 'Alert Rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('triggered_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('event_count', models.IntegerField(help_text='Number of events that triggered the alert')),
                ('details', models.JSONField(default=dict, help_text='Details about the alert (IPs, countries, etc)')),
                ('notifications_sent', models.JSONField(default=list, help_text='List of notifications sent (channel, status, timestamp)')),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], default='medium', max_length=20)),
                ('acknowledged', models.BooleanField(db_index=True, default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_alerts', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alert_history', to='organizations.organization')),
                ('alert_rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='alerts.alertrule')),
            ],
            options={
                'verbose_name': 'Alert History',
                'verbose_name_plural': 'Alert Histories',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationChannel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('channel_type', models.CharField(choices=[('email', 'Email'), ('slack', 'Slack'), ('discord', 'Discord'), ('webhook', 'Generic Webhook')], max_length=20)),
                ('name', models.CharField(help_text='Friendly name for this channel', max_length=255)),
                ('config', models.JSONField(default=dict, help_text='Channel configuration (encrypted webhooks, email lists, etc)')),
                ('enabled', models.BooleanField(db_index=True, default=True)),
                ('verified', models.BooleanField(default=False, help_text='Has this channel been tested/verified?')),
                ('last_used', models.DateTimeField(blank=True, null=True)),
                ('total_notifications', models.IntegerField(default=0)),
                ('failed_notifications', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_notification_channels', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_channels', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Notification Channel',
                'verbose_name_plural': 'Notification Channels',
                'ordering': ['channel_type', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['organization', 'enabled'], name='alerts_aler_organiz_59ceeb_idx'),
        ),
        migrations.AddIndex(
            model_name='alertrule',
            index=models.Index(fields=['organization', 'last_triggered'], name='alerts_aler_organiz_46279a_idx'),
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['organization', 'triggered_at'], name='alerts_aler_organiz_a025e3_idx'),
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['organization', 'acknowledged'], name='alerts_aler_organiz_1f4651_idx'),
        ),
        migrations.AddIndex(
            model_name='alerthistory',
            index=models.Index(fields=['alert_rule', 'triggered_at'], name='alerts_aler_alert_r_4ea5a5_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['organization', 'enabled'], name='alerts_noti_organiz_903759_idx'),
        ),
        migrations.AddIndex(
            model_name='notificationchannel',
            index=models.Index(fields=['organization', 'channel_type'], name='alerts_noti_organiz_7df056_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='notificationchannel',
            unique_together={('organization', 'channel_type', 'name')},
        ),
    ]
