# Generated by Django 5.2.8 on 2025-11-13 10:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SecurityLog',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('source_type', models.CharField(choices=[('haproxy', 'HAProxy'), ('nginx', 'Nginx'), ('crowdsec', 'CrowdSec'), ('fail2ban', 'Fail2ban')], db_index=True, max_length=20)),
                ('source_host', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('src_ip', models.GenericIPAddressField(db_index=True)),
                ('src_port', models.IntegerField(blank=True, null=True)),
                ('dst_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('dst_port', models.IntegerField(blank=True, null=True)),
                ('protocol', models.CharField(blank=True, max_length=10)),
                ('method', models.CharField(blank=True, max_length=10)),
                ('path', models.TextField(blank=True)),
                ('user_agent', models.TextField(blank=True)),
                ('status_code', models.IntegerField(blank=True, null=True)),
                ('bytes_sent', models.BigIntegerField(blank=True, null=True)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny'), ('ban', 'Ban'), ('challenge', 'Challenge'), ('rate_limit', 'Rate Limit')], db_index=True, max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('country_code', models.CharField(blank=True, max_length=2)),
                ('raw_log', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Security Log',
                'verbose_name_plural': 'Security Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
