# Generated by Django 5.2.8 on 2025-11-13 10:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logs', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='securitylog',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='security_logs', to='organizations.organization'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['organization', 'timestamp'], name='logs_securi_organiz_95a6dc_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['organization', 'src_ip'], name='logs_securi_organiz_331732_idx'),
        ),
    ]
