# Generated by Django 5.2.8 on 2025-11-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0002_initial'),
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='securitylog',
            name='logs_securi_organiz_331732_idx',
        ),
        migrations.RemoveField(
            model_name='securitylog',
            name='protocol',
        ),
        migrations.AddField(
            model_name='securitylog',
            name='asn',
            field=models.CharField(blank=True, db_index=True, help_text='Autonomous System Number', max_length=20),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='country_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='geo_enriched',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='geo_enriched_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='isp',
            field=models.CharField(blank=True, help_text='Internet Service Provider', max_length=255),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='org',
            field=models.CharField(blank=True, help_text='Organization name', max_length=255),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='region',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='securitylog',
            name='timezone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='action',
            field=models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny'), ('ban', 'Ban'), ('rate_limit', 'Rate Limit'), ('challenge', 'Challenge')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='country_code',
            field=models.CharField(blank=True, db_index=True, help_text='ISO 3166-1 alpha-2 country code', max_length=2),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='path',
            field=models.CharField(blank=True, max_length=2048),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='raw_log',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='severity',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='source_type',
            field=models.CharField(choices=[('haproxy', 'HAProxy'), ('nginx', 'Nginx'), ('crowdsec', 'CrowdSec'), ('fail2ban', 'Fail2ban')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='status_code',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='securitylog',
            name='user_agent',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['src_ip', 'timestamp'], name='logs_securi_src_ip_0c0930_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['action', 'severity'], name='logs_securi_action_9f15bf_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['source_type', 'timestamp'], name='logs_securi_source__a01fa5_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['country_code', 'timestamp'], name='logs_securi_country_a33180_idx'),
        ),
        migrations.AddIndex(
            model_name='securitylog',
            index=models.Index(fields=['geo_enriched'], name='logs_securi_geo_enr_057c8a_idx'),
        ),
    ]
