# Generated by Django 5.2.8 on 2025-11-18 08:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logs', '0003_remove_securitylog_logs_securi_organiz_331732_idx_and_more'),
        ('organizations', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_hostname', models.CharField(db_index=True, help_text='Original hostname from security logs', max_length=255)),
                ('display_name', models.CharField(help_text='Custom display name for this server', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional description of server purpose')),
                ('server_type', models.CharField(blank=True, help_text='Server type: web, api, database, etc', max_length=50)),
                ('environment', models.CharField(choices=[('production', 'Production'), ('staging', 'Staging'), ('development', 'Development'), ('testing', 'Testing')], default='production', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this server is currently active')),
                ('last_seen', models.DateTimeField(blank=True, help_text='Last time logs were received from this server', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_server_aliases', to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='server_aliases', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Server Alias',
                'verbose_name_plural': 'Server Aliases',
                'ordering': ['display_name'],
                'unique_together': {('organization', 'original_hostname')},
            },
        ),
    ]
