# Generated by Django 5.2.8 on 2025-12-30 00:00

import uuid
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("logs", "0005_service_snapshot"),
    ]

    operations = [
        migrations.CreateModel(
            name="InventorySnapshot",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("source_host", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(db_index=True)),
                ("payload", models.JSONField(default=dict)),
                ("organization", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="inventory_snapshots", to="organizations.organization")),
            ],
        ),
    ]
