# Generated by Django 5.2.8 on 2025-11-13 10:35

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=100, unique=True, validators=[django.core.validators.RegexValidator(message='Slug can only contain lowercase letters, numbers, and hyphens.', regex='^[a-z0-9-]+$')])),
                ('is_active', models.BooleanField(default=True)),
                ('max_users', models.IntegerField(default=5)),
                ('max_api_keys', models.IntegerField(default=3)),
                ('max_logs_per_month', models.IntegerField(default=1000000)),
                ('subscription_tier', models.CharField(choices=[('free', 'Free'), ('starter', 'Starter'), ('professional', 'Professional'), ('enterprise', 'Enterprise')], default='free', max_length=20)),
                ('subscription_ends_at', models.DateTimeField(blank=True, null=True)),
                ('log_retention_days', models.IntegerField(default=90)),
                ('enable_email_notifications', models.BooleanField(default=True)),
                ('enable_slack_notifications', models.BooleanField(default=False)),
                ('slack_webhook_url', models.URLField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'verbose_name': 'Organization',
                'verbose_name_plural': 'Organizations',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='organizatio_slug_048085_idx'), models.Index(fields=['is_active'], name='organizatio_is_acti_1ffc28_idx')],
            },
        ),
        migrations.CreateModel(
            name='APIKey',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('name', models.CharField(max_length=100)),
                ('key_prefix', models.CharField(db_index=True, max_length=10, unique=True)),
                ('key_hash', models.CharField(max_length=255)),
                ('can_ingest', models.BooleanField(default=True)),
                ('allowed_sources', models.JSONField(default=list, help_text="List of allowed sources: ['haproxy', 'nginx', 'crowdsec', 'fail2ban']")),
                ('rate_limit', models.CharField(default='1000/hour', help_text="Rate limit in format: '1000/hour'", max_length=20)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('total_requests', models.BigIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrganizationMember',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('admin', 'Admin'), ('analyst', 'Analyst'), ('readonly', 'Read Only')], default='readonly', max_length=20)),
                ('can_manage_users', models.BooleanField(default=False)),
                ('can_manage_api_keys', models.BooleanField(default=False)),
                ('can_create_alerts', models.BooleanField(default=False)),
                ('can_export_data', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='organizations.organization')),
            ],
            options={
                'verbose_name': 'Organization Member',
                'verbose_name_plural': 'Organization Members',
            },
        ),
    ]
