# Generated by Django 5.2.8 on 2025-11-18 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='agent',
            name='secret_hash',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='agent',
            name='secret_prefix',
            field=models.CharField(blank=True, db_index=True, max_length=12),
        ),
        migrations.AddField(
            model_name='agent',
            name='secret_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
